lsi: false
safe: true
incremental: false
highlighter: rouge
markdown: kramdown
site.github: {
  "owner_name": "dmeloca",
  "owner_url": "https://github.com/dmeloca",
}
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
